const sabores = [
    { n: "4 Queijos", d: "Molho, Mussarela, Parmesão, Provolone, Gorgonzola, Azeitona e Orégano", g: 51, b: 38 },
    { n: "5 Queijos", d: "Molho, Mussarela, Parmesão, Provolone, Gorgonzola, Catupiry, Azeitona e Orégano", g: 53, b: 40 },
    { n: "Abobrinha 1", d: "Molho, Mussarela, Abobrinha, Alho, Azeitona e Orégano", g: 44, b: 34 },
    { n: "Abobrinha 2", d: "Molho, Mussarela, Abobrinha, Pimenta Calabresa, Azeitona e Orégano", g: 44, b: 34 },
    { n: "Alho", d: "Molho, Mussarela, Alho, Azeitona e Orégano", g: 44, b: 33 },
    { n: "Aliche", d: "Molho, Mussarela, Aliche, Azeitona e Orégano", g: 52, b: 39 },
    { n: "Aliche 2", d: "Molho, Mussarela, Aliche, Cheiro Verde, Azeitona e Orégano", g: 54, b: 40 },
    { n: "Americana", d: "Molho, Mussarela, Champignon, Lombinho, Tomate Cereja, Pimentão, Provolone, Azeitona e Orégano", g: 56, b: 42 },
    { n: "Atum 1", d: "Molho, Atum, Cebola, Azeitona e Orégano", g: 50, b: 37 },
    { n: "Atum 2", d: "Molho, Mussarela, Atum, Cebola, Azeitona e Orégano", g: 55, b: 39 },
    { n: "Atum 3", d: "Molho, Atum, Catupiry, Cebola, Azeitona e Orégano", g: 55, b: 39 },
    { n: "Bacon 1", d: "Molho, Mussarela, Bacon, Azeitona e Orégano", g: 49, b: 36 },
    { n: "Bacon 2", d: "Molho, Mussarela, Tomate Cereja, Bacon, Alho, Azeitona e Orégano", g: 52, b: 38 },
    { n: "Baiana", d: "Molho, Mussarela, Calabresa Desfiada, Pimenta Calabresa, Ovo, Cebola, Azeitona e Orégano", g: 50, b: 37 },
    { n: "Brócolis 1", d: "Molho, Mussarela, Brócolis, Bacon, Azeitona e Orégano", g: 50, b: 38 },
    { n: "Brócolis 2", d: "Molho, Mussarela, Brócolis, Bacon, Alho, Azeitona e Orégano", g: 51, b: 39 },
    { n: "Calabresa 1", d: "Molho, Calabresa, Cebola, Azeitona e Orégano", g: 42, b: 30 },
    { n: "Calabresa 2", d: "Molho, Mussarela, Calabresa, Cebola, Azeitona e Orégano", g: 47, b: 34 },
    { n: "Calapy", d: "Molho, Calabresa, Catupiry, Cebola, Azeitona e Orégano", g: 48, b: 34 },
    { n: "Escarola", d: "Molho, Mussarela, Escarola, Parmesão, Alho, Azeitona e Orégano", g: 47, b: 37 },
    { n: "Frango Bacon", d: "Molho, Frango, Catupiry, Bacon, Azeitona e Orégano", g: 55, b: 40 },
    { n: "Frango & Catupiry", d: "Molho, Frango, Catupiry, Azeitona e Orégano", g: 51, b: 39 },
    { n: "Gênova 1", d: "Molho, Mussarela, Presunto, Provolone, Molho Pesto, Azeitona e Orégano", g: 51, b: 39 },
    { n: "Gênova 2", d: "Molho, Mussarela, Lombinho, Provolone, Molho Pesto, Azeitona e Orégano", g: 52, b: 39 },
    { n: "Libanese", d: "Molho, Mussarela, Tomate, Zatar, Azeitona e Orégano", g: 44, b: 31 },
    { n: "Lombinho", d: "Molho, Mussarela, Lombinho, Provolone, Azeitona e Orégano", g: 51, b: 38 },
    { n: "Marguedoro", d: "Molho, Mussarela, Tomate, Parmesão, Alho, Manjericão, Azeitona e Orégano", g: 45, b: 32 },
    { n: "Marguerita", d: "Molho, Mussarela, Tomate, Parmesão, Manjericão, Azeitona e Orégano", g: 44, b: 31 },
    { n: "Marguerita Pesto", d: "Molho, Mussarela, Tomate, Parmesão, Molho Pesto, Azeitona e Orégano", g: 45, b: 31 },
    { n: "Mussapy", d: "Molho, Mussarela, Tomate, Catupiry, Azeitona e Orégano", g: 48, b: 35 },
    { n: "Mussarela", d: "Molho, Mussarela, Tomate, Azeitona e Orégano", g: 42, b: 30 },
    { n: "Peperonni", d: "Molho, Mussarela, Peperonni, Azeitona e Orégano", g: 53, b: 40 },
    { n: "Peperonni 2", d: "Molho, Mussarela, Peperonni, Catupiry, Azeitona e Orégano", g: 58, b: 45 },
    { n: "Pomodoro", d: "Molho, Mussarela, Tomate, Parmesão, Alho, Azeitona e Orégano", g: 49, b: 35 },
    { n: "Portuguesa", d: "Molho, Mussarela, Presunto, Ovo, Ervilha, Tomate, Azeitona e Orégano", g: 54, b: 40 },
    { n: "Potatosa 1", d: "Molho, Batata, Parmesão, Calabresa Desfiada, Catupiry, Azeitona e Orégano", g: 50, b: 36 },
    { n: "Potatosa 2", d: "Molho, Batata, Parmesão, Bacon, Catupiry, Azeitona e Orégano", g: 51, b: 36 },
    { n: "Romana", d: "Molho, Mussarela, Aliche, Tomate, Azeitona e Orégano", g: 52, b: 40 },
    { n: "Rúcula & Tomate Seco", d: "Molho, Mussarela, Rúcula, Tomate Seco, Azeitona e Orégano", g: 50, b: 37 },
    { n: "Rústica", d: "Molho, Mussarela, Parmesão, Sobre Molho de Tomate, Azeitona e Orégano", g: 47, b: 33 },
    { n: "Toscana", d: "Molho, Mussarela, Calabresa Desfiada, Cebola, Azeitona e Orégano", g: 49, b: 36 },
    { n: "Toscana 2", d: "Molho, Mussarela, Calabresa Desfiada, Cebola, Alecrim, Provolone, Azeitona e Orégano", g: 52, b: 38 },
    { n: "Vitorelli", d: "Molho, Mussarela, Presunto, Gorgonzola, Azeitona e Orégano", g: 50, b: 40 },

    // DOCES
    { n: "Anita & Garibaldi", d: "Mussarela, Parmesão e Goiabada", g: 46, b: 35 },
    { n: "Banana & Doce de Leite", d: "Banana, Açúcar, Doce de Leite e Canela", g: 42, b: 31 },
    { n: "Ovomaltini", d: "Creme de Leite e Ovomaltine", g: 56, b: 45 }
];

const bebidas = [
    { n: "Coca Cola 2Lt", d: "Refrigerante", p: 18 },
    { n: "Guaraná Kuat", d: "Refrigerante", p: 12 },
    { n: "Cerveja Lata", d: "Cerveja", p: 8 }
];
